# Generated by Django 4.2.23 on 2025-07-10 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('shopping', 'Shopping'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('food', 'Food'), ('health', 'Health'), ('bills', 'Bills & Utilities'), ('subscriptions', 'Subscriptions'), ('education', 'Education'), ('others', 'Others')], default='others', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
